# Generated by Django 2.2.3 on 2019-07-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20190725_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportbyday',
            name='row_count',
            field=models.IntegerField(default=0),
        ),
    ]
