# Generated by Django 2.2.3 on 2019-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_reportbyday_row_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportByMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start_time', models.BigIntegerField()),
                ('month_minimum_time', models.BigIntegerField()),
                ('month_maximum_time', models.BigIntegerField()),
                ('sum_opening_value', models.FloatField(null=True)),
                ('max_opening_value', models.FloatField(null=True)),
                ('min_opening_value', models.FloatField(null=True)),
                ('sum_closing_value', models.FloatField(null=True)),
                ('max_closing_value', models.FloatField(null=True)),
                ('min_closing_value', models.FloatField(null=True)),
                ('max_high_value', models.FloatField(null=True)),
                ('min_high_value', models.FloatField(null=True)),
                ('max_low_value', models.FloatField(null=True)),
                ('min_low_value', models.FloatField(null=True)),
                ('sum_volumne_in_btc', models.FloatField(null=True)),
                ('max_volumne_in_btc', models.FloatField(null=True)),
                ('min_volumne_in_btc', models.FloatField(null=True)),
                ('sum_volumne_in_currency', models.FloatField(null=True)),
                ('max_volumne_in_currency', models.FloatField(null=True)),
                ('min_volumne_in_currency', models.FloatField(null=True)),
                ('sum_weighted_price', models.FloatField(null=True)),
                ('max_weighted_price', models.FloatField(null=True)),
                ('min_weighted_price', models.FloatField(null=True)),
                ('row_count', models.IntegerField(default=0)),
            ],
        ),
    ]
