# Generated by Django 2.2.3 on 2019-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_reportbymonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbyday',
            name='day_maximum_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportbyday',
            name='day_minimum_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportbymonth',
            name='month_maximum_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportbymonth',
            name='month_minimum_time',
            field=models.BigIntegerField(null=True),
        ),
    ]
