# Generated by Django 2.2.3 on 2019-07-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_timestamp', models.BigIntegerField()),
                ('opening_value', models.FloatField(null=True)),
                ('closing_value', models.FloatField(null=True)),
                ('high_value', models.FloatField(null=True)),
                ('low_value', models.FloatField(null=True)),
                ('volumne_in_btc', models.FloatField(null=True)),
                ('volumne_in_currency', models.FloatField(null=True)),
                ('weighted_price', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'btc_data',
            },
        ),
    ]
